version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: hercules-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
      - "8441:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./docker/certbot/www:/var/www/certbot:ro
    depends_on:
      - vue-frontend
      - bagisto-backend
    networks:
      - hercules-network

  vue-frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: hercules-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - hercules-network

  bagisto-backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: hercules-backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=bagisto
      - DB_USERNAME=hercules
      - DB_PASSWORD=secret
      - LOKI_HOST=inqed-loki
      - LOKI_PORT=3100
    networks:
      - hercules-network
      - inqed-monitoring

  postgres:
    image: postgres:15-alpine
    container_name: hercules-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=bagisto
      - POSTGRES_USER=hercules
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hercules-network

  redis:
    image: redis:alpine
    container_name: hercules-redis
    restart: unless-stopped
    networks:
      - hercules-network

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: hercules-mailpit
    restart: unless-stopped
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - hercules-network

networks:
  hercules-network:
    driver: bridge
  inqed-monitoring:
    external: true

volumes:
  postgres-data:
  node_modules:
